


#' Defining an Arm
#'
#' @description
#' Define an arm in trial
#'
#' @param name name of arm, which is the arm's label in generated data
#' @param ... subset condition that is compatible with \code{dplyr::filter}.
#' This can be used to specify inclusion criteria of an arm.
#' By default it is not specified, i.e. all data generated by the generator
#' will be used as trial data. More than one conditions can be
#' specified in \code{...}.
#'
#' @returns a summary report (html) of the endpoints in the arm accounting for
#' subset conditions if executed in console
#'
#' @export
#'
#' @examples
#' ## see vignette:
#' ## https://zhangh12.github.io/TrialSimulator/articles/defineArms.html
#'
arm <- function(name, ...){

  TrialSimulator::arm(name = name, ...)

}
